FROM pietroastolfi/tractogram-filtering:cpu-1.0

MAINTAINER Pietro, Ruben and Paolo

# tractogram filtering
RUN git clone https://github.com/FBK-NILab/tractogram_filtering.git \
    && cd tractogram_filtering \
    && git checkout miccai2020
  
ENV PATH=/tractogram_filtering:$PATH
